# frozen_string_literal: true

source 'http://rubygems.org'
ruby '3.4.10'

gem 'google-protobuf'
gem 'sorbet-runtime'
gem 'twirp'

group :development do
  gem 'rubocop', require: false
  gem 'solargraph'
  gem 'sorbet'
end

group :development, :test do
  gem 'tapioca', require: false
end
