# frozen_string_literal: true
# typed: strict

require_relative 'base_object'
require_relative 'account'

module Types
  # GraphQL type for the Entity model
  class Entity < BaseObject
    field :id, ID, null: false
    field :name, String, null: false
    field :holder_uuid, ID, null: false
    field :created_at, GraphQL::Types::ISO8601DateTime, null: false
    field :updated_at, GraphQL::Types::ISO8601DateTime, null: false
    field :accounts, [Types::Account], null: false,
                                       description: 'Financial accounts held by this entity.'

    # DB column backing each scalar field, keyed by the field's Ruby name.
    COLUMNS_BY_FIELD = T.let({
      id: :id,
      name: :name,
      holder_uuid: :holder_uuid,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze, T::Hash[Symbol, Symbol])

    class << self
      # Scopes `dataset` down to the columns the requested entity fields need, and
      # eager-loads `accounts` (with its own column selection) when requested, so
      # paginating `entities` never issues one `accounts` query per row.
      #
      # `Models::Entity::PrivateDataset` is a static-only fiction generated by
      # `sorbet/tapioca/compilers/sequel_model.rb` — it never exists as a real
      # constant at runtime, so a normal `sig` referencing it would raise
      # `NameError` the first time this method is called. `T::Sig::WithoutRuntime.sig`
      # gets the same static checking (typo'd method names, wrong arity, etc. on
      # the `.select`/`.eager` chain below are still caught by `srb tc`) without
      # ever forcing the block at runtime.
      T::Sig::WithoutRuntime.sig do
        params(lookahead: GraphQL::Execution::Lookahead, dataset: Models::Entity::PrivateDataset)
          .returns(Models::Entity::PrivateDataset)
      end
      def scope(lookahead, dataset)
        node_lookaheads = node_selections(lookahead)
        # `T.unsafe` here is a Sorbet limitation, not a Sequel one: splatting an
        # array whose length isn't known statically (`selected_columns` returns a
        # plain `T::Array[Symbol]`) into any method call is unsupported — see
        # https://srb.help/7019. `dataset.select` itself stays fully typed.
        scoped = dataset.select(*T.unsafe(selected_columns(node_lookaheads)))
        eager_accounts(scoped, node_lookaheads)
      end

      private

      sig { params(node_lookaheads: T::Array[GraphQL::Execution::Lookahead]).returns(T::Array[Symbol]) }
      def selected_columns(node_lookaheads)
        COLUMNS_BY_FIELD.each_with_object([:id]) do |(field, column), columns|
          columns << column if column != :id && node_lookaheads.any? { |node| node.selects?(field) }
        end
      end

      T::Sig::WithoutRuntime.sig do
        params(dataset: Models::Entity::PrivateDataset, node_lookaheads: T::Array[GraphQL::Execution::Lookahead])
          .returns(Models::Entity::PrivateDataset)
      end
      def eager_accounts(dataset, node_lookaheads)
        account_lookaheads = node_lookaheads.filter_map { |node| node.selection(:accounts) }.select(&:selected?)
        return dataset if account_lookaheads.empty?

        account_columns = account_lookaheads.flat_map { |al| Types::Account.selected_columns(al) }.uniq
        # The foreign key must be selected even though it isn't a GraphQL field:
        # Sequel matches each eagerly-loaded account back to its entity by this
        # column's value, and won't add it back in for us once we've called
        # `select` ourselves.
        foreign_key = Models::Entity.association_reflection(:accounts).fetch(:key)
        dataset.eager(accounts: proc { |ds| ds.select(*(account_columns | [foreign_key])) })
      end

      # A relay connection can be walked via `edges { node { ... } }` or via
      # `nodes { ... }` — a client may use either, so look under both rather than
      # assuming one.
      sig { params(lookahead: GraphQL::Execution::Lookahead).returns(T::Array[GraphQL::Execution::Lookahead]) }
      def node_selections(lookahead)
        [lookahead.selection(:nodes), lookahead.selection(:edges).selection(:node)].select(&:selected?)
      end
    end
  end
end
